# 使用 Ubuntu 20.04 作为基础镜像
FROM ubuntu:20.04

# 更新 Ubuntu 软件包
RUN apt-get update

# 安装 Python 3.8
RUN apt-get install -y python3.8

# 安装 Java 1.8
RUN apt-get install -y openjdk-8-jdk

# 设置环境变量
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
ENV PATH=$PATH:$JAVA_HOME/bin

# 设置工作目录
WORKDIR /app